### PR TITLE
Feature/improve readme file

### PR DESCRIPTION
**Pull request by we-satyajeet-s001**
I have updated readme.md file based on the modifications which is done on the test scripts.

### CODE REVIEW

**Comment by themodernpk** [comment]
@satyajeet-s001 you must also write about how to define unique `Test ID`

**Comment by we-satyajeet-s001** [comment]
sir, i have updated how and why to define unique test count id. Please review it once.

**Comment by we-satyajeet-s001** [comment]
Sir tried to fix all the changes as you said..

**Comment by we-satyajeet-s001** [comment]
good afternoon sir . done with all the changes.

**Pull request merged**
